// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLXoam6v6MoSM7aPPBiAgjHE8h05oBqQ',
    appId: '1:7333257234:web:7a30b187ac971b831ff8cb',
    messagingSenderId: '7333257234',
    projectId: 'flutterscript-691ea',
    authDomain: 'flutterscript-691ea.firebaseapp.com',
    storageBucket: 'flutterscript-691ea.firebasestorage.app',
    measurementId: 'G-TTXQ5800GQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAweXn1B8ku41Ujt48Z7Wu_WOSEs0oZhOQ',
    appId: '1:7333257234:ios:ea0874c33ff3a9b51ff8cb',
    messagingSenderId: '7333257234',
    projectId: 'flutterscript-691ea',
    storageBucket: 'flutterscript-691ea.firebasestorage.app',
    iosBundleId: 'com.example.serviceBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAweXn1B8ku41Ujt48Z7Wu_WOSEs0oZhOQ',
    appId: '1:7333257234:ios:ea0874c33ff3a9b51ff8cb',
    messagingSenderId: '7333257234',
    projectId: 'flutterscript-691ea',
    storageBucket: 'flutterscript-691ea.firebasestorage.app',
    iosBundleId: 'com.example.serviceBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLXoam6v6MoSM7aPPBiAgjHE8h05oBqQ',
    appId: '1:7333257234:web:27c6664952dde4651ff8cb',
    messagingSenderId: '7333257234',
    projectId: 'flutterscript-691ea',
    authDomain: 'flutterscript-691ea.firebaseapp.com',
    storageBucket: 'flutterscript-691ea.firebasestorage.app',
    measurementId: 'G-Y0MB6HCE40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG761odhq8yy8u-HceMWiP6ED_9J3hd_o',
    appId: '1:7333257234:android:a2ddc2a3f7eb8c631ff8cb',
    messagingSenderId: '7333257234',
    projectId: 'flutterscript-691ea',
    storageBucket: 'flutterscript-691ea.firebasestorage.app',
  );

}